language: android
jdk: oraclejdk7
env:
  matrix:
    - ANDROID_TARGET=android-19 ANDROID_ABI=armeabi-v7a

before_install:
  # workaround for travis-ci/travis-ci#2279
  - 'sudo mv /usr/local/android-sdk/tools/android-* /usr/local/bin'
  # Accept all licenses (workaround for travis-ci/travis-ci#2466)
  # Upgrade 'platform-tools' before 'tools' (workaround for travis-ci/travis-ci#2470)
  # Run dinstinct 'android update sdk' commands
  - "android-update-sdk --components='platform-tools,tools' --accept-licenses='.+'"
  - "android-update-sdk --components='build-tools-20.0.0' --accept-licenses='.+'"
  - "android-update-sdk --components='android-20' --accept-licenses='.+'"
  - "android-update-sdk --components='extra-android-m2repository,extra-google-m2repository,extra-android-support'--accept-licenses='.+'"

#android:
#  components:
#    - tools
#    - platform-tools
#    - build-tools-20.0.0
#    - extra-android-support
#    - android-20
#  licenses:
#    - android-sdk-license-5be876d5
#    - android-sdk-license-598b93a6

before_script:
  # Create and start emulator
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - adb wait-for-device
  - adb shell input keyevent 82 &

script: ./gradlew connectedCheck